### ISSUE TITLE
INFO exited: blueiris (exit status 1; not expected)

### ISSUE THREAD

**Issue by ycodryn** [jshridha/docker-blueiris#44] opened 2021-02-02 13:59 UTC
Using the vaapi dockerfiles, after creating the container and running it, I`m getting that message. Also using -v /volume1/docker/blueiris:/home/wineuser/prefix:rw, container is not creating files inside mapped volume
edit: all my containers are created with my main user uid/gid and all are working correctly but this one refuse to create files inside mapped volume. I tried to change /home/wineuser/prefix with /root/prefix on all files inside docker before creation and now is semi populating the mapped volume.

**Comment by brillopaul** [comment] 2021-02-07 05:39
Good Evening I am experiencing a similar issue. Here is a screen capture of the error I am receiving:
![image](https://user-images.githubusercontent.com/78675379/107140804-31ad2980-68ea-11eb-9894-f5b37b24101e.png)

**Comment by jshridha** [comment] 2021-02-11 11:32
Can you both try to manually chown the data directory from the host to be the proper user and then restart the container? I think the issue is that the permissions aren't being set properly on first run.

e.g. `chown -R 1000:1000 ./data`

**Comment by ghost** [comment] 2021-02-11 12:56
I'm using unraid and had the same issue. Thank you @jshridha for the obvious fix :)

**Comment by ycodryn** [comment] 2021-02-12 11:05
Thanks jshridha I will try tonight, all my containers are created with main root user uid/gid so mybe this is the problem.

**Comment by jshridha** [comment] 2021-02-13 04:47
This is fixed in: 651429e1688232489729beda836bf271719a0b94 Permissions on data directory are now set at startup. Builds take a while but should hit docker hub soon.

Feel free to reopen if the issue persists for you. Thanks for posting!

**Closed as completed by jshridha** 2021-02-13 04:47 UTC
