### ISSUE TITLE
Version 4

### ISSUE THREAD

**Issue by pratik5705** [jshridha/docker-blueiris#20] opened 2020-05-21 20:58 UTC
Per instructions at https://hub.docker.com/r/jshridha/blueiris, I can run version 4 using variable BLUEIRIS_VERISION=4. I have this set, but still it is downloading version 5.

**Comment by OscarVanL** [comment] 2020-06-15 01:18
Did you find a resolution to this? I see the container hasn't been updated in 6 months so I assume this is still a problem?

**Comment by OscarVanL** [comment] 2020-06-15 01:25
I can see that in `blueiris.sh` if the executable is missing it runs `wget http://blueirissoftware.com/blueiris.exe`. 

The problem is, this `blueiris.exe` is for Blue Iris 5. I can see on the [download page](https://blueirissoftware.com/#download) the correct URL for Blue Iris 4 would be `https://blueirissoftware.com/BlueIris_48603.exe`. 

This could be fixed by modifying the `blueiris.sh` file to check the runtime variable's value and download from the appropriate link.

**Here's a hotfix to get your container up and running:**

1. List the names of the containers.
`sudo docker ps` 

2. Open a bash shell to the container
`docker exec -it <container name>  /bin/bash` 

3. Remove the existing blueiris installer (if present)
`rm blueiris.exe`

4. Edit the script (I hope you know how to use vim! Otherwise `apt-get install nano` and use `nano blueiris.sh`, which is probably easier.)
`vim blueiris.sh` 

5. Change `wget http://blueirissoftware.com/blueiris.exe` to `wget https://blueirissoftware.com/BlueIris_48603.exe`

6. Add this line right after the wget line (keep the same indentation):
`mv BlueIris_48603.exe blueiris.exe`

7. Change the expected BLUEIRIS_EXE path from `/root/prefix32/drive_c/Program Files/Blue Iris 5/BlueIris.exe` to `/root/prefix32/drive_c/Program Files/Blue Iris 4/BlueIris.exe`

(If you don't do this, the container will repeatedly run the installer)

Now restart the container, connect to VNC (`<IP>:8080/vnc.html`) and complete the installation.

Hope that helps :)

**Comment by OscarVanL** [comment] 2020-06-15 11:54
So it turns out this is already fixed. Instead of installing the `latest` Docker build, get the `dev` Docker build and this will work as intended and the above steps are not necessary.

**Comment by jshridha** [comment] 2020-06-15 12:06
I'm working on fixing the build and then it'll be incorporated into master and you can just pull the latest tag and run that.

**Comment by OscarVanL** [comment] 2020-06-15 12:12
Awesome :) Thanks

**Closed as completed** 2020-08-30 09:10 UTC
